### ISSUE TITLE
MissingPluginException while running Demo

### ISSUE THREAD

**Issue by nduc86686** [jiusanzhou/flutter_floatwing#13]
Hi,I have a problem running the application
`E/flutter (18685): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method window.start on channel im.zoe.labs/flutter_floatwing/window)
E/flutter (18685): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (18685): <asynchronous suspension>
E/flutter (18685): #1      Window.start (package:flutter_floatwing/src/window.dart:114:12)
E/flutter (18685): <asynchronous suspension>
E/flutter (18685): 
`

**Comment by nduc86686** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22623.891], locale vi-VN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.8)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by rorystephenson** [comment]
@nduc86686 I've seen something similar but I think the root cause is an exception that happens before that one. Try the fix in #19 .

**Comment by remarkked** [comment]
@rorystephenson last main commit same exception
