### ISSUE TITLE
使用flutter 3.7.5运行example点击assitive_touch出现异常。

### ISSUE THREAD

**Issue by rise-worlds** [jiusanzhou/flutter_floatwing#18]
flutter doctor -v
Flutter assets will be downloaded from https://mirror.sjtu.edu.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.7.5, on Microsoft Windows [版本 10.0.22621.1265], locale en-US)
    • Flutter version 3.7.5 on channel stable at D:\Github\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (2 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://mirror.sjtu.edu.cn/dart-pub
    • Flutter download mirror https://mirror.sjtu.edu.cn
点击assitive_touch出现异常。
PlatformException (PlatformException(error, java.lang.Long cannot be cast to java.lang.Integer, null, java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at im.zoe.labs.flutter_floatwing.FloatWindow$Config$Companion.from(FloatWindow.kt:502)
	at im.zoe.labs.flutter_floatwing.FloatWindow.onMethodCall(FloatWindow.kt:221)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6197)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
))

**Comment by rise-worlds** [comment]
使用git上的代碼沒有問題
